export type Locale = "en" | "tl";

export type Translations = Record<string, string | Record<string, string | Record<string, string>>>;

export const translations: Record<Locale, Translations> = {
  en: {
    nav: { home: "Home", services: "Services", gallery: "Gallery", about: "About", contact: "Contact" },
    hero: { badge: "Calauag's trusted nail salon", tagline: "Beautiful Nails for Every Occasion", description: "Professional manicure and pedicure services in Calauag, Quezon. Book online or via Messenger.", bookNow: "Book Now", messageUs: "✈ Message Us" },
    services: { title: "Our Services", subtitle: "Professional nail care services tailored to your style", empty: "No services available yet. Check back soon!", bookNow: "Book Now", minutes: "minutes", min: "min", orViaMessenger: "✈ Or Book via Messenger", pageTitle: "Our Services", pageSubtitle: "Professional nail care for every occasion" },
    gallery: { title: "Our Work", subtitle: "See the latest designs and styles from our salon", viewFull: "View Full Gallery", alt: "Nail art by Karen Manicures", pageTitle: "Gallery", pageSubtitle: "Browse our latest nail art and designs", empty: "Gallery coming soon! Check back later.", altFallback: "Nail art" },
    about: { title: "About Karen", para1: "With over 10 years of experience in the beauty industry, Karen has been providing exceptional nail care services to the Calauag community. Her passion for nail art and dedication to customer satisfaction has made Karen Manicures a trusted name in town.", para2: "Every service is performed with precision, care, and the highest quality products. Whether you need a simple classic manicure or an elaborate gel design, Karen ensures you leave with a smile.", pageTitle: "About Karen Manicures", pagePara1: "Welcome to Karen Manicures, your premier nail care destination in Calauag, Quezon. We are dedicated to providing exceptional nail services in a relaxing and welcoming environment.", pagePara2: "With over a decade of experience in the beauty industry, Karen has perfected the art of nail care. From classic manicures to intricate gel designs, every service is performed with attention to detail and a commitment to quality.", pagePara3: "Our salon uses only high-quality products and follows strict hygiene standards to ensure your safety and satisfaction. We believe that beautiful nails are not just about appearance — they are about confidence and self-care.", pagePara4: "Whether you are preparing for a special occasion or simply treating yourself, we look forward to welcoming you to Karen Manicures." },
    testimonials: { title: "What Our Clients Say", review1: "Best nails in Calauag! Karen always does an amazing job. Highly recommended!", name1: "Maria Santos", review2: "I've been coming here for years. The gel manicures last for weeks. Love it!", name2: "Ana Torres", review3: "Very professional and friendly service. The salon is always clean and relaxing.", name3: "Beth Cruz" },
    contact: { title: "Visit Us", subtitle: "We would love to see you! Drop by the salon or book online.", address: "Address", phone: "Phone", email: "Email", businessHours: "Business Hours", bookOnline: "Book Online", messageViaMessenger: "✈ Message via Messenger", pageTitle: "Contact Us" },
    footer: { quickLinks: "Quick Links", contact: "Contact", hours: "Hours", copyright: "All rights reserved.", builtBy: "Built by", dataNotice: "We collect booking information to manage appointments. See our Privacy Policy for details." },
    booking: { title: "Book an Appointment", stepService: "Service", stepDateTime: "Date & Time", stepInfo: "Your Info", chooseService: "Choose a Service", serviceEmpty: "No services available at the moment.", selectDateTime: "Select Date & Time", availableTimes: "Available times for", loadingTimes: "Loading available times...", errorTimes: "Could not load available times. Please try again.", noSlots: "No available slots for this date", back: "← Back", next: "Next →", yourInfo: "Your Information", fullName: "Full Name *", namePlaceholder: "Maria Santos", phoneNumber: "Phone Number *", phonePlaceholder: "0917 123 4567", phoneHelper: "We will send a confirmation SMS to this number", emailOptional: "Email (optional)", emailPlaceholder: "maria@email.com", notes: "Notes (optional)", notesPlaceholder: "Any special requests?", booking: "Booking...", confirmBooking: "Confirm Booking", pendingTitle: "Booking Submitted!", confirmedTitle: "Appointment Booked!", pendingMsg: "Your booking needs approval from Karen. You will receive a notification once confirmed.", confirmedMsg: "You will receive a confirmation SMS at your provided number.", changesMsg: "Need to make changes? Message Karen on Messenger.", messageOnMessenger: "✈ Message on Messenger", anotherBooking: "Book Another Appointment", backToHome: "Back to Home", errorGeneric: "Something went wrong" },
    days: { monday: "Monday", tuesday: "Tuesday", wednesday: "Wednesday", thursday: "Thursday", friday: "Friday", saturday: "Saturday", sunday: "Sunday", closed: "Closed" },
    common: { menu: "Menu", messenger: "✈ Messenger", bookNow: "Book Now", messageOnMessenger: "✈ Message on Messenger", loading: "Loading...", save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", yes: "Yes", no: "No", confirm: "Confirm" },
    legal: { privacy: "Privacy Policy", terms: "Terms of Service", smsConsent: "I agree to receive SMS reminders about my appointment", lastUpdated: "Last updated", collect: "What We Collect", collectDesc: "We collect only the information you provide when booking an appointment:", useInfo: "How We Use Your Information", useInfoDesc: "Your information is used solely to:", retention: "Data Retention", retentionDesc: "Appointment data is retained for up to 12 months. You may request deletion by contacting Karen directly.", consent: "Your Consent", consentDesc: "By booking an appointment, you consent to the collection and use of your information as described above.", contact: "Contact", contactDesc: "If you have questions about this policy, please contact Karen at:", bookingConfirm: "Booking Confirmation", bookingConfirmDesc: "Your appointment is confirmed when you receive a confirmation SMS or email. If you do not receive confirmation within 24 hours, please contact Karen directly.", cancellation: "Cancellation Policy", cancellationDesc: "Please notify Karen at least 24 hours in advance if you need to cancel or reschedule. Cancellations with less than 24 hours notice may affect your ability to book in the future.", noShow: "No-Show Policy", noShowDesc: "If you do not arrive for your appointment without prior notice, it will be recorded as a no-show. Repeated no-shows may result in refusal of future bookings.", payment: "Payment", paymentDesc: "Payment is collected at the salon after your service. We accept cash and GCash." },
  },
  tl: {
    nav: { home: "Home", services: "Mga Serbisyo", gallery: "Gallery", about: "Tungkol sa Amin", contact: "Makipag-ugnayan" },
    hero: { badge: "Pinagkakatiwalaang nail salon sa Calauag", tagline: "Magagandang Kuko para sa Bawat Okasyon", description: "Propesyonal na serbisyo ng manikyur at pedikyur sa Calauag, Quezon. Mag-book online o sa pamamagitan ng Messenger.", bookNow: "Mag-book Na", messageUs: "✈ Mag-message" },
    services: { title: "Aming mga Serbisyo", subtitle: "Propesyonal na pangangalaga ng kuko na nababagay sa iyong estilo", empty: "Wala pang serbisyo. Balik ka mamaya!", bookNow: "Mag-book Na", minutes: "minuto", min: "min", orViaMessenger: "✈ O Mag-book sa Messenger", pageTitle: "Aming mga Serbisyo", pageSubtitle: "Propesyonal na pangangalaga ng kuko para sa bawat okasyon" },
    gallery: { title: "Aming mga Gawa", subtitle: "Tingnan ang aming mga pinakabagong disenyo at estilo", viewFull: "Tingnan ang Buong Gallery", alt: "Disenyo ng kuko ni Karen Manicures", pageTitle: "Gallery", pageSubtitle: "Tingnan ang aming mga pinakabagong nail art at disenyo", empty: "Ang gallery ay darating pa! Balik ka mamaya.", altFallback: "Disenyo ng kuko" },
    about: { title: "Tungkol kay Karen", para1: "Sa mahigit 10 taong karanasan sa industriya ng kagandahan, si Karen ay nagbibigay ng pambihirang serbisyo sa pangangalaga ng kuko sa komunidad ng Calauag. Ang kanyang pagkahilig sa nail art at dedikasyon sa kasiyahan ng kliyente ay ginawa ang Karen Manicures na isang pinagkakatiwalaang pangalan sa bayan.", para2: "Ang bawat serbisyo ay ginagawa nang may katumpakan, pangangalaga, at pinakamataas na kalidad ng mga produkto. Kung kailangan mo ng simpleng classic manicure o masalimuot na gel design, titiyakin ni Karen na aalis kang nakangiti.", pageTitle: "Tungkol kay Karen Manicures", pagePara1: "Maligayang pagdating sa Karen Manicures, ang inyong pangunahing destinasyon para sa pangangalaga ng kuko sa Calauag, Quezon. Kami ay nakatuon sa pagbibigay ng pambihirang serbisyo sa nail care sa isang nakakarelaks at nakakaengganyang kapaligiran.", pagePara2: "Sa mahigit isang dekada ng karanasan sa industriya ng kagandahan, pinaghusay ni Karen ang sining ng pangangalaga ng kuko. Mula sa classic manicures hanggang sa masalimuot na gel designs, ang bawat serbisyo ay ginagawa nang may atensyon sa detalye at pangako sa kalidad.", pagePara3: "Ang aming salon ay gumagamit lamang ng mga de-kalidad na produkto at sumusunod sa mahigpit na pamantayan sa kalinisan upang matiyak ang iyong kaligtasan at kasiyahan. Naniniwala kami na ang magagandang kuko ay hindi lamang tungkol sa itsura — ito ay tungkol sa kumpyansa at pag-aalaga sa sarili.", pagePara4: "Kung ikaw ay naghahanda para sa isang espesyal na okasyon o nagpapasaya lamang sa iyong sarili, inaasahan naming kayo ay tanggapin sa Karen Manicures." },
    testimonials: { title: "Ano ang Sabi ng Aming mga Kliyente", review1: "Pinakamagagandang kuko sa Calauag! Si Karen ay palaging gumagawa ng magandang trabaho. Lubos na inirerekomenda!", name1: "Maria Santos", review2: "Ilang taon na akong pumupunta rito. Ang gel manicures ay tumatagal nang ilang linggo. Gustung-gusto ko ito!", name2: "Ana Torres", review3: "Napaka-propesyonal at magiliw na serbisyo. Ang salon ay palaging malinis at nakakarelaks.", name3: "Beth Cruz" },
    contact: { title: "Bumisita sa Amin", subtitle: "Gusto ka naming makita! Bumisita sa salon o mag-book online.", address: "Tirahan", phone: "Telepono", email: "Email", businessHours: "Oras ng Trabaho", bookOnline: "Mag-book Online", messageViaMessenger: "✈ Mag-message sa Messenger", pageTitle: "Makipag-ugnayan sa Amin" },
    footer: { quickLinks: "Mga Link", contact: "Makipag-ugnayan", hours: "Oras", copyright: "Lahat ng karapatan ay nakalaan.", builtBy: "Ginawa ng", dataNotice: "Kinokolekta namin ang impormasyon ng booking upang pamahalaan ang mga appointment. Tingnan ang aming Patakaran sa Pagkapribado para sa mga detalye." },
    booking: { title: "Mag-book ng Appointment", stepService: "Serbisyo", stepDateTime: "Petsa at Oras", stepInfo: "Iyong Impormasyon", chooseService: "Pumili ng Serbisyo", serviceEmpty: "Walang serbisyo sa ngayon.", selectDateTime: "Pumili ng Petsa at Oras", availableTimes: "Mga available na oras para sa", loadingTimes: "Naglo-load ng mga available na oras...", errorTimes: "Hindi makapag-load ng mga available na oras. Pakisubukan muli.", noSlots: "Walang available na slot para sa petsang ito", back: "← Bumalik", next: "Susunod →", yourInfo: "Iyong Impormasyon", fullName: "Buong Pangalan *", namePlaceholder: "Maria Santos", phoneNumber: "Numero ng Telepono *", phonePlaceholder: "0917 123 4567", phoneHelper: "Magpapadala kami ng confirmation SMS sa numerong ito", emailOptional: "Email (opsyonal)", emailPlaceholder: "maria@email.com", notes: "Tala (opsyonal)", notesPlaceholder: "May espesyal na kahilingan?", booking: "Nagbo-book...", confirmBooking: "Kumpirmahin ang Booking", pendingTitle: "Na-submit ang Booking!", confirmedTitle: "Naka-book na ang Appointment!", pendingMsg: "Ang iyong booking ay nangangailangan ng approval mula kay Karen. Makakatanggap ka ng abiso kapag nakumpirma na.", confirmedMsg: "Makakatanggap ka ng confirmation SMS sa iyong ibinigay na numero.", changesMsg: "Kailangan ng pagbabago? Mag-message kay Karen sa Messenger.", messageOnMessenger: "✈ Mag-message sa Messenger", anotherBooking: "Mag-book ng Ibang Appointment", backToHome: "Bumalik sa Home", errorGeneric: "May error na nangyari" },
    days: { monday: "Lunes", tuesday: "Martes", wednesday: "Miyerkules", thursday: "Huwebes", friday: "Biyernes", saturday: "Sabado", sunday: "Linggo", closed: "Sarado" },
    common: { menu: "Menu", messenger: "✈ Messenger", bookNow: "Mag-book Na", messageOnMessenger: "✈ Mag-message sa Messenger", loading: "Naglo-load...", save: "I-save", cancel: "Kanselahin", delete: "Burahin", edit: "I-edit", yes: "Oo", no: "Hindi", confirm: "Kumpirmahin" },
    legal: { privacy: "Patakaran sa Pagkapribado", terms: "Mga Tuntunin ng Serbisyo", smsConsent: "Sumasang-ayon akong makatanggap ng SMS paalala tungkol sa aking appointment", lastUpdated: "Huling na-update", collect: "Ano ang Aming Kinokolekta", collectDesc: "Kinokolekta lang namin ang impormasyong ibinigay mo kapag nagbu-book ng appointment:", useInfo: "Paano Namin Ginagamit ang Iyong Impormasyon", useInfoDesc: "Ang iyong impormasyon ay ginagamit lamang para sa:", retention: "Pag-iimbak ng Data", retentionDesc: "Ang data ng appointment ay iniimbak hanggang 12 buwan. Maaari kang humiling ng pagbura sa pamamagitan ng pagkontak kay Karen.", consent: "Iyong Pahintulot", consentDesc: "Sa pagbu-book ng appointment, pumapayag ka sa pagkolekta at paggamit ng iyong impormasyon tulad ng nakasaad sa itaas.", contact: "Makipag-ugnayan", contactDesc: "Kung may tanong ka tungkol sa patakarang ito, mangyaring kontakin si Karen sa:", bookingConfirm: "Kumpirmasyon ng Booking", bookingConfirmDesc: "Ang iyong appointment ay kumpirmado kapag nakatanggap ka ng SMS o email ng kumpirmasyon. Kung hindi ka makatanggap ng kumpirmasyon sa loob ng 24 oras, mangyaring kontakin si Karen.", cancellation: "Patakaran sa Pagkansela", cancellationDesc: "Mangyaring ipaalam kay Karen nang hindi bababa sa 24 oras bago kung kailangan mong magkansela o mag-reschedule. Ang pagkansela nang wala pang 24 oras na abiso ay maaaring makaapekto sa iyong kakayahang mag-book sa hinaharap.", noShow: "Patakaran sa Hindi Pagdating", noShowDesc: "Kung hindi ka dumating sa iyong appointment nang walang paunang abiso, ito ay itatala bilang no-show. Ang paulit-ulit na no-show ay maaaring magresulta sa pagtanggi ng mga susunod na booking.", payment: "Pagbabayad", paymentDesc: "Ang pagbabayad ay kinokolekta sa salon pagkatapos ng iyong serbisyo. Tumatanggap kami ng cash at GCash." },
  },
};

export function getTranslation(locale: Locale, key: string): string {
  const keys = key.split(".");
  let value: Translations | string = translations[locale];
  for (const k of keys) {
    if (typeof value === "object" && k in value) {
      value = value[k];
    } else {
      return key;
    }
  }
  return typeof value === "string" ? value : key;
}
